CREATE TABLE IF NOT EXISTS User (
    id TEXT PRIMARY KEY,
    firstName TEXT NOT NULL,
    lastName TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    isSetUp BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS AuthClient (
    id TEXT PRIMARY KEY,
    clientId TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    ownerId TEXT,
    FOREIGN KEY (ownerId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RedirectURI (
    id TEXT PRIMARY KEY,
    uri TEXT NOT NULL,
    authClientId TEXT,
    FOREIGN KEY (authClientId) REFERENCES AuthClient(id) ON DELETE CASCADE
);