# Generated by Django 5.1.3 on 2024-11-12 10:12

import authlib.oauth2.rfc6749.models
import django.db.models.deletion
import oauth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2AuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=48)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('redirect_uri', models.TextField(default='', null=True)),
                ('response_type', models.TextField(default='')),
                ('scope', models.TextField(default='', null=True)),
                ('auth_time', models.IntegerField(default=oauth.models.now_timestamp)),
                ('nonce', models.CharField(default='', max_length=120, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, authlib.oauth2.rfc6749.models.AuthorizationCodeMixin),
        ),
    ]
