CREATE TABLE IF NOT EXISTS User (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    firstName TEXT NOT NULL,
    lastName TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    isSetUp BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS AuthClient (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    clientId TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    ownerId INTEGER,
    FOREIGN KEY (ownerId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RedirectURI (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uri TEXT NOT NULL,
    authClientId INTEGER,
    FOREIGN KEY (authClientId) REFERENCES AuthClient(id) ON DELETE CASCADE
);